import React from 'react';
import { useRouter } from 'next/router';
import data from '../../public/data.json'
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar'
import Navbar2 from '@/components/Navbar2';
import Footer from '@/components/Footer';
import Footer2 from '@/components/Footer2';
import Head from 'next/head'
import Image from 'next/image'

function Post() {
  const router = useRouter();
  const { id } = router.query;

  console.log(id)

  console.log(data)

  const post = data.find(post => post.id == id);

  console.log(post)

  if (!post) return

  return (
    <div className>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar pageWrapId={"page-wrap"} outerContainerId={"Home"} />
      <Navbar2 />
      <div>
        <div className="box">
        
          <div className="brushed-title-container-cover post-brush-title">
              <h2 className="brushi">{post.subject}</h2>
          </div>
          
          <div class="col-lg-12 post-image">
                <Image
                  src={`/../public/images/posts/${post.id}.jpg`}
                  width={1024}
                  height={500}
                  alt={post.subject}
                  className="blog-post-image"
                />
          </div>
          
          <div class="col-lg-12 post-content">
              {post.content}
          </div>
          
          <div class="col-lg-12 post-author-container">
            <div class="post-author">
              {post.author}
            </div>
          </div>

        </div>
      </div>
      <Footer2 />
      <Footer />
    </div>
  );
}

export default Post;
