import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Cover from '../components/Cover'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar>
        <title>inSTrukcije</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Navbar>
      <Cover />
      <Main />
      <Footer />
    </div>
  )
}
