import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Cover from '../components/Cover'
import Cover1 from '../components/Cover1'
import Cover2 from '../components/Cover2'
import Cover3 from '../components/Cover3'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar>
        <title>inSTrukcije</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Navbar>
      <Cover />
      <Cover1 />
      <Cover2 />
      <Cover3 />
      <Footer />
    </div>
  )
}
