import React from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import Blog from '../components/Blog.js';
import data from '../public/data.json'
import Navbar from '@/components/Navbar';
import Sidebar from '../components/Sidebar'
import Navbar2 from '@/components/Navbar2';
import Footer from '@/components/Footer';
import Footer2 from '@/components/Footer2';
import Head from 'next/head'

function Petplus() {
  return (
    <div className>
      <Head>
        <title>5+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar pageWrapId={"page-wrap"} outerContainerId={"Home"} />
      <Navbar2 />
      <Blog posts={data} />
      <Footer2 />
      <Footer />
    </div>
  );
}

export default Petplus;
