import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Navbar from '../components/Navbar'
import Navbar2 from '../components/Navbar2'
import Footer from '@/components/Footer'
import Footer2 from '@/components/Footer2'
import Subjects1 from '@/components/Subjects1'
import PriceList from '@/components/PriceList'
const inter = Inter({ subsets: ['latin'] })

export default function Cjenik() {
  return (
    <div className>
      <Head>
        <title>Cjenik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Navbar2 />
      <Subjects1 />
      <PriceList />
      <Footer2 />
      <Footer />
    </div>
  )
}
