import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Navbar from '../components/Navbar'
import Navbar2 from '../components/Navbar2'
import Footer from '../components/Footer'
import Footer2 from '../components/Footer2'
import BundlePack  from '../components/BundlePack'
import Bundle  from '../components/Bundle'
import BundlePackdm  from '../components/BundlePackdm'
import Bundledm  from '../components/Bundledm'

const inter = Inter({ subsets: ['latin'] })

export default function Predmeti() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Predmeti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Navbar2 />
      <Bundle />
      <BundlePack />
      <Bundledm />
      <BundlePackdm />
      <Footer2 />
      <Footer />
    </div>
  )
}
