import React from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import Blog from '../components/Blog.js'; // Import your BlogComponent
import data from '../public/data.json'
import Navbar from '@/components/Navbar';
import Navbar2 from '@/components/Navbar2';
import Footer from '@/components/Footer';
import Footer2 from '@/components/Footer2';
import Head from 'next/head'
import { useRouter } from 'next/router';

function StaroPosts() {
  const router = useRouter();
  const { id } = router.query;

  const post = data.find(post => post.id === id);

  if (!post) return

  return (
    <div className>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Navbar2 />
      <div>
        {post.content}
      </div>
      <Footer2 />
      <Footer />
    </div>
  );
}

export default StaroPosts ;
